### ISSUE TITLE
Daily Build on Clouds

### ISSUE THREAD

**Issue by alpha-rudy** [alpha-rudy/taiwan-topo#1]
Suggest from Rex by using docker 10 minutes is needed.

**Comment by alpha-rudy** [comment]
Finally done, this is done by Google GCE. What a powerful tool!

**Comment by kcwu** [comment]
How long does it need for one build?

**Comment by alpha-rudy** [comment]
Hi @kcwu, it is one hour for 3 maps (bw, odc, mapsforge).

I'm currently using a free account (limited to 8 vCPUs and RAM) and preemptive availability. So, it may be faster after I began to pay.  ^^

Rudy  12/7

**Comment by kcwu** [comment]
Wow, much faster than the speed you said (one day) on facebook. So, there is probably no need to optimize for now?

**Comment by alpha-rudy** [comment]
Yes, @kcwu, at least not with a high priority.  ^^
