### ISSUE TITLE
Survey Vectorial Map Lite

### ISSUE THREAD

**Issue by alpha-rudy** [alpha-rudy/taiwan-topo#10]
https://www.facebook.com/groups/taiwan.topo/permalink/706639036158379/

Law Ling
> 另提供一個ios離線地圖登山APP，支援ASTER.OSM - Taiwan TOPO地圖格式，
但是不能使用本社團開發離線地圖，均顯示錯誤，有點可惜！
本軟體是我發覺在ios運行較佳的登山APP，看看能否支援！
Harald Meyer 的 Vectorial Map Lite

**Comment by alpha-rudy** [comment]
https://www.facebook.com/groups/taiwan.topo/permalink/706639036158379/?comment_id=706786566143626&comment_tracking=%7B%22tn%22%3A%22R%22%7D

Law Ling

> 能否有辦法將地圖格式轉成為mbtiles格式？
> 本人在使用ios系統，真的歷盡滄桑，要找個像樣的軌跡記錄APP，不是缺東缺西，無法與android系統完整，而知名軟體又無力或不願開發ios介面，真的遺憾！
> 所以，以下這二個軟體，地圖僅支援mbtiles格式，尤其「地圖加加」導航能力非常棒，平常登山健行，以此為主要工具。盼是否可轉換的可能性？
> Miocool Inc. 的 地圖加加（GIS編輯 + 離線地圖 + 軌跡記錄）
> https://appsto.re/tw/OJjkA.i
> Builtsoft 的 やまやまGPS (登山、渓流釣り、MTB用地図)
> https://appsto.re/tw/MDaCD.i

**Comment by chihchun** [comment]
理論上可以用 Mobile Atlas Creator (MOBAC) 吃 mapsforge 輸出成 MBTiles. 所需空間會大很多。

**Comment by alpha-rudy** [comment]
Thanks, @chihchun, 你知道哪裡有說明文件嗎？

**Comment by alpha-rudy** [comment]
No needed. Closed.  ^^
