### ISSUE TITLE
docker file 缺少安裝 tools 的步驟

### ISSUE THREAD

**Issue by kcwu** [alpha-rudy/taiwan-topo#16]
我發現 build script 會用到一些 tools 裡的程式, 但 docker file 裡沒有 install 也沒有設 PATH.

**Comment by kcwu** [comment]
我發現我誤會了, osmconvert 是用 apt-get 裝的那份, 不是 tools 裡那份

**Comment by alpha-rudy** [comment]
喔，我到沒有發現 tools 裡有。謝謝！  :D
