### ISSUE TITLE
Remove sea/bounds not used to minimum the disk space

### ISSUE THREAD

**Issue by alpha-rudy** [alpha-rudy/taiwan-topo#18]
"請問 taiwan-topo 裡的 bounds 跟 sea 目錄的檔案, 是下載來的還是程式產生的? 我在想能不能只留台灣的部份, 或是用下載的. 這樣 git 裡就不會那麼大"
--- KC Wu

**Comment by alpha-rudy** [comment]
Wow, our taiwan-topo begins as a cooperative project.  ^^b

**Comment by alpha-rudy** [comment]
Let's have the issue closed, until the next time.  ^^

**Comment by kcwu** [comment]
我剛剛 rewrite git history, 把台灣之外的 bound file 都砍掉了
(這次我只砍 bounds; 沒有動 sea)

原本 git checkout 之後,
.git 目錄占 2.3 GB, bounds 目錄 1.8 GB, 全部 4.6 GB
現在
.git 目錄占 1 GB, bounds 目錄 6 MB, 全部 1.8 GB

曾 checkout 的朋友, @happyman, @typebrook , @alpha-rudy FYI, 麻煩請重新 git clone
