### ISSUE TITLE
Support OsmAnd format

### ISSUE THREAD

**Issue by alpha-rudy** [alpha-rudy/taiwan-topo#20]
OBF map could be made by, ...

    $ make SUITE=taiwan osmand

Style could be made by, ...

    $ make SUITE=taiwan osmand_style

And these two targets should be included in `all` targets.

**Comment by alpha-rudy** [comment]
OsmAnd on iOS has no way to use customized style file, which results the appearing of maps no good for hiking. 

Discussed with Rex, give up OsmAnd.

**Comment by kcwu** [comment]
How about file a bug in https://github.com/osmandapp/OsmAnd-ios/issues for customized style?
