### ISSUE TITLE
zoom 18 以上涼亭的標示消失

### ISSUE THREAD

**Issue by chihchun** [alpha-rudy/taiwan-topo#21]
今天去波津加山，發現一個問題，放大倍數到 18 以上，涼亭的標示消失 如附圖[1] - 

[1] https://www.facebook.com/groups/taiwan.topo/permalink/733527420136207/
[2] http://mc.basecamp.tw/#16/24.2224/121.0098

**Comment by alpha-rudy** [comment]
Hi @chihchun, Got it!  Thanks!  :D

**Comment by alpha-rudy** [comment]
Hi @chihchun, 請問。mc.basecamp.tw 上的 "Rudy Taiwan TOPO" 所使用的 style 是 "MOI_OSM" 嗎？

（Trail 看起來不是紅色虛線）
<img width="556" alt="screen shot 2017-01-02 at 2 33 50 pm" src="https://cloud.githubusercontent.com/assets/12744709/21585309/853fd8ec-d0f8-11e6-9838-d76ae0cca11c.png">

**Comment by alpha-rudy** [comment]
Render Theme is totally correct at the setting. It seems to be caused by a bug at mapsforge render engine. 

What could be done is to work around by thinker trail beside the alpine hub.
