### ISSUE TITLE
Support MAPS.ME

### ISSUE THREAD

**Issue by alpha-rudy** [alpha-rudy/taiwan-topo#22]
Referred to the link, ...
https://www.facebook.com/groups/taiwan.topo/permalink/730051410483808/?comment_id=734536200035329&comment_tracking=%7B%22tn%22%3A%22R%22%7D

**Comment by alpha-rudy** [comment]
Hi @kcwu, @chihchun, help please!  :)

I cannot even build the MWM generator tool, ...

    $ CONFIG=gtool omim/tools/unix/build_omim.sh -ro

I referred from https://github.com/mapsme/omim/blob/master/docs/INSTALL.md.

Could you help? Thank you!

Rudy  1/9

**Comment by kcwu** [comment]
https://github.com/mapsme/omim/blob/master/docs/INSTALL.md 中間這行壞掉
```
sudo add-apt-repository ppa:jhe/llvm-toolchain
```
(bug: https://github.com/mapsme/omim/issues/5515)

若跳過那行, 我現在可以進行到 storage.cpp compile fail
```
/omim/storage/storage.cpp:1108:15: error: no matching member function for call to 'erase'
      m_queue.erase(it);
```
不曉得是 storage.cpp 後來改版, 還是因為 toolchain 版本不對

**Comment by alpha-rudy** [comment]
我建了一台 ubuntu 14.04 在 GCP，KC 兄，也可以試試。

**Comment by alpha-rudy** [comment]
叫做 omim-builder，目前也失敗在 

    $ CONFIG=gtool omim/tools/unix/build_omim.sh -ro

**Comment by alpha-rudy** [comment]
其中的錯誤，我覺得很有可能是 llvm-toolchain 不夠新。

```
--------------------
In file included from /home/rudychung/omim/3party/opening_hours/rules_evaluation.hpp:3:0,
                 from /home/rudychung/omim/3party/opening_hours/rules_evaluation.cpp:1:
/home/rudychung/omim/3party/opening_hours/opening_hours.hpp:162:31: error: missing space between '""' and suffix identifier
 inline constexpr Time::THours operator ""_h(unsigned long long int h)
                               ^
```

程式如下：
```
rudychung@omit-builder:~$ tail -n+162 omim/3party/opening_hours/opening_hours.hpp | head -n 4
inline constexpr Time::THours operator ""_h(unsigned long long int h)
{
  return Time::THours(h);
}
```

**Comment by alpha-rudy** [comment]
怪哉，升級到 3.9.1 之後，結果一樣。

```
$ sudo vi /etc/apt/sources.list
$ sudo apt-get update
$ sudo apt-get install llvm-3.9 clang-3.9
$ sudo ln -sf /usr/lib/llvm-3.9/bin/clang /usr/bin/clang
$ sudo ln -sf /usr/lib/llvm-3.9/bin/clang++ /usr/bin/clang++
$ clang --version
clang version 3.9.1-svn288847-1~exp1 (branches/release_39)

$ rm -rf omim-build-release/
$ CONFIG=gtool omim/tools/unix/build_omim.sh
```

**Comment by alpha-rudy** [comment]
我把，Qt 5.5 environment 加到 .bash_profile，@kcwu 可以直接 compile 看看。  ^^
（仍然無法成功）

```
source /opt/qt55/bin/qt55-env.sh
```

**Comment by alpha-rudy** [comment]
Let's close the request, until the next time.  XD
