### ISSUE TITLE
地圖產生器出圖

### ISSUE THREAD

**Issue by happyman** [alpha-rudy/taiwan-topo#24]
1. landcover 關閉，但也希望能夠顯示崩壁，可行嗎?
2. 各種字仍然太小。
能夠協助解決嗎? 還是教我們怎麼調整?
![233000x2488000-2x2-v2016 tag](https://cloud.githubusercontent.com/assets/82296/23118024/88ec13e6-f78d-11e6-8a38-f743e65a12e6.png)

**Comment by alpha-rudy** [comment]
@happyman 兄，收到！  :)

1. 可行。
2. 可以試試，是否有類似, ...
    * OruxMaps 中 地圖/地圖設定/Mapsforge 設定/Mapsforge文字大小 （試試 1.5 看看）
    * Locus Maps 中 選項/地圖/離線地圖/字體大小 （試試 150%）

**Comment by happyman** [comment]
![226000x2492000-3x2-v2016 tag](https://cloud.githubusercontent.com/assets/82296/23742931/c46a0540-04e9-11e7-9a4c-f7db44bb02ae.png)
崩壁有了。謝謝。
我的 fontscale 已經是 1.5 了說。

**Comment by happyman** [comment]
![image](https://cloud.githubusercontent.com/assets/82296/23743684/985cdd4e-04ec-11e7-9ef3-3b3f50e49cad.png)
跟經建三版比起來，自型跟線條都可以再霸氣一點。

**Comment by alpha-rudy** [comment]
reopen!  :)

**Comment by alpha-rudy** [comment]
嗨， @happyman 兄，調整好了。請看看 FB 上的截圖，並給予意見。謝謝！   ：）
(https://www.facebook.com/groups/taiwan.topo/permalink/773816942773921/)

**Comment by happyman** [comment]
上一個版本
![image](https://cloud.githubusercontent.com/assets/82296/24072292/3490594a-0c20-11e7-9c14-65becc85843f.png)
今天的修改
![image](https://cloud.githubusercontent.com/assets/82296/24072288/1739e3b6-0c20-11e7-8a1f-3f1504393905.png)
看起來還是不夠霸氣耶

**Comment by alpha-rudy** [comment]
@happyman 兄，還是不夠霸氣？  XD

你可以 scroll 上去一點點，討論的歷史中有個連結，可以看到我的修改 (https://github.com/alpha-rudy/taiwan-topo/commit/575ae8e1ddebddf8b5277eb74c1b0eeb5168879f )。

大致上，修改可以分成三個部分，
* 最上面是背景
* 中間是 contour line 的顏色
* 後面是字型

由你的附圖，我看起來像是有山形陰影的顯示。或許是造成非純白的原因。可否取消山形陰影看看。
另字型可以再放大。我有點擔心對手機而言會太大了，或許我改字體顏色看看。  ^^

**Comment by happyman** [comment]
謝謝說明。或許我得針對輸出搞一個 style。
目前我用 mobac 的 renderer 參數如下:
elmt-accommodation-b=false
elmt-accommodation-c=false
elmt-accommodation-h=false
elmt-accommodation-m=false
elmt-amenities-b=true
elmt-amenities-c=true
elmt-amenities-h=true
elmt-amenities-m=true
elmt-barriers-b=true
elmt-barriers-c=true
elmt-barriers-h=true
elmt-barriers-m=true
elmt-borders-b=true
elmt-borders-c=true
elmt-borders-h=true
elmt-borders-m=true
elmt-buildings-b=false
elmt-buildings-c=false
elmt-buildings-h=false
elmt-buildings-m=false
elmt-c_routes=true
elmt-c_s_routes=false
elmt-car-b=false
elmt-car-c=false
elmt-car-h=true
elmt-car-m=false
elmt-city=false
elmt-contour-c=true
elmt-cycling=false
elmt-emergency-b=false
elmt-emergency-c=false
elmt-emergency-h=false
elmt-emergency-m=false
elmt-h_routes=true
elmt-h_s_routes=false
elmt-hiking=true
elmt-landcover=false
elmt-landscapefeat-b=true
elmt-landscapefeat-c=true
elmt-landscapefeat-h=true
elmt-landscapefeat-m=true
elmt-mtb=false
elmt-mtb_c_routes=false
elmt-mtb_routes=true
elmt-mtb_s_routes=false
elmt-outdoorsports-b=true
elmt-outdoorsports-c=false
elmt-outdoorsports-h=true
elmt-outdoorsports-m=true
elmt-pt_network=false
elmt-pubtrans-b=false
elmt-pubtrans-c=true
elmt-pubtrans-h=true
elmt-pubtrans-m=false
elmt-restaurants-b=true
elmt-restaurants-c=true
elmt-restaurants-h=true
elmt-restaurants-m=true
elmt-settlements-b=true
elmt-settlements-c=true
elmt-settlements-h=true
elmt-settlements-m=true
elmt-shops-b=false
elmt-shops-c=true
elmt-shops-h=false
elmt-shops-m=false
elmt-tourism-b=false
elmt-tourism-c=true
elmt-tourism-h=true
elmt-tourism-m=false
elmt-waymarks=false

請問陰影是哪一個呢?

**Comment by alpha-rudy** [comment]
嗨， @happyman 兄，mapsforge 的圖資本身（含 style）並沒有包含 hillshading。

是不是我的眼睛看久了，看花了，感覺你的附圖有很明顯 hillshading 的明暗處理。

mobac 我也沒用過。可能要求救一下 Rex 兄。  ^^

**Comment by alpha-rudy** [comment]
嗨， @happyman 兄，我把手機螢幕截圖下來。點擊在空白處，的確是 #FFFFFF 的白色哩。

<img width="724" alt="screen shot 2017-03-18 at 9 58 01 pm" src="https://cloud.githubusercontent.com/assets/12744709/24072721/2ff730d8-0c26-11e7-9f1a-6505d407c920.png">

**Comment by alpha-rudy** [comment]
手機上的原始截圖 zoom 16：

![screenshot_20170318-215632](https://cloud.githubusercontent.com/assets/12744709/24072740/75be6348-0c26-11e7-933d-0bf7e76d5fdf.jpg)

**Comment by alpha-rudy** [comment]
Hi, @happyman 兄，我有個想法。

Zoom 加一級，使用 17，但實際顯示大小仍維持同樣大小。有點像 width="50%" 這樣的顯示方式。或許顯示結果會好一點。

**Comment by happyman** [comment]
![image](https://cloud.githubusercontent.com/assets/82296/24076712/b7a102ba-0c72-11e7-9562-dd5c9c602836.png)
![image](https://cloud.githubusercontent.com/assets/82296/24076741/88137914-0c73-11e7-901a-49e998a93d9f.png)


目前調整出以下設定
``

    <rule e="way" k="contour_ext" v="*" zoom-min="16" zoom-max="16">
      <rule e="way" k="contour_ext" v="elevation_minor">
        <line stroke="#948C85" stroke-width="0.2"/>
      </rule>
      <rule e="way" k="contour_ext" v="elevation_sub">
        <line stroke="#948C85" stroke-width="0.35"/>
      </rule>
      <rule e="way" k="contour_ext" v="elevation_medium">
        <line stroke="#948C85" stroke-width="0.45"/>
      </rule>
      <rule e="way" k="contour_ext" v="elevation_major">
        <line stroke="#730016" stroke-width="0.5"/>
      </rule>
    </rule>
跟 contour 的字


    <rule e="way" k="contour_160m" v="*" zoom-min="16" zoom-max="16">
      <rule e="way" k="contour_160m" v="elevation_minor">
        <pathText k="ele" font-size="10" fill="#000000" stroke="#FFFFFFFF" stroke-width="2"/>
      </rule>
      <rule e="way" k="contour_160m" v="elevation_medium">
        <pathText k="ele" font-size="12" fill="#000000" stroke="#FFFFFFFF" stroke-width="2"/>
      </rule>
      <rule e="way" k="contour_160m" v="elevation_major">
        <pathText k="ele" font-size="12" font-style="bold" fill="#000000" stroke="#FFFFFFFF" stroke-width="2"/>
      </rule>

灰階輸出看起來好多了。
針對輸出 z=16, 希望 1. 水線顏色希望能夠加深 2.  山頭字加大，不要加上高度

**Comment by happyman** [comment]
https://github.com/alpha-rudy/taiwan-topo/pull/25/commits/d2c0fe2701ebdb98f6663b1c34614ffdd26b5ac2

**Comment by happyman** [comment]
![image](https://cloud.githubusercontent.com/assets/82296/26673042/10c00aa2-46ee-11e7-863b-f5f4b59f0aa1.png)
總算把把水色弄深了。
