### ISSUE TITLE
Suggestion: use 7z to compress zip

### ISSUE THREAD

**Issue by kcwu** [alpha-rudy/taiwan-topo#26]
7zip (tool) 也可以用來壓縮 zip 格式, 壓縮率比一般的 zip 高.

譬如在我機器上(freebsd), 測試資料 20170701 MOI beta

size | compress time | command line
---- | -------------- | ----------------
404997696 | - | (`MOI_OSM_Taiwan_TOPO_Rudy.map`)
335104185 | - | (`MOI_OSM_Taiwan_TOPO_Rudy.map.zip`)
335104185 | 34s | `zip a.zip MOI_OSM_Taiwan_TOPO_Rudy.map`
331159556 | 39s| `7z a -tzip a.zip MOI_OSM_Taiwan_TOPO_Rudy.map`
330121448 | 105s | `7z a -tzip -mx=7 a.zip MOI_OSM_Taiwan_TOPO_Rudy.map`
329719415 | 362s | `7z a -tzip -mx=9 a.zip MOI_OSM_Taiwan_TOPO_Rudy.map`

所以也許可以用 7z 的 zip 壓縮(mx 沒指定預設是 5), 差不多的壓縮時間可以省 4mb.

**Comment by alpha-rudy** [comment]
嗨， @kcwu 兄，抱歉晚回了。  XD
請問 7z 在 iOS, Android, Mac, PC 上，都可以用嗎？

**Comment by kcwu** [comment]
7z 這個程式可以產生不同格式的壓縮檔(包含 7z 格式, 也有 zip 格式). 這個 ticket 的建議是用 7z 程式, 但仍用 zip 格式, 所以使用者一樣都能解壓縮.

如果你是問7z壓縮程式的支援, 除了 android 我不確定, 各平台都有.

BTW, 將來有下載程式幫忙, 以後我們可以考慮使用更好的壓縮格式.

**Comment by alpha-rudy** [comment]
Got it. Thanks, @kcwu !  :)

**Comment by alpha-rudy** [comment]
Done. It will be working after v2018.03.15.  :)
