### ISSUE TITLE
無法編譯 Couldn't open file /root/osm_elevations/ele_taiwan_10_100_500_moi.osm.pbf

### ISSUE THREAD

**Issue by ayeteng** [alpha-rudy/taiwan-topo#27]
在makefile中有一段是
ELEVATIONS_URL := file://${HOME}/osm_elevations
$(ELEVATION):
	[ -n "$(REGION)" ]
	mkdir -p $(ELEVATIONS_DIR)
	cd $(ELEVATIONS_DIR) && \
	    curl -k $(ELEVATIONS_URL)/$(ELEVATION_FILE) -o $(ELEVATION_FILE) && \
	    curl -k $(ELEVATIONS_URL)/$(ELEVATION_FILE).md5 -o $(ELEVATION_FILE).md5 && \
	    EXAM_FILE=$@; [ "$$($(MD5_CMD))" == "$$(cat $(ELEVATION_FILE).md5 | cut -d' ' -f1)" ] || \
	    	( rm -rf $@ && false )

如果編譯都會出現錯誤

[root@mw-sw31 taiwan-topo]# make SUITE=taiwan mapsforge
[ -n "Taiwan" ]
mkdir -p /home/gps/taiwan-topo/download/osm_elevations
cd /home/gps/taiwan-topo/download/osm_elevations && \
    curl -k file:///root/osm_elevations/ele_taiwan_10_100_500_moi.osm.pbf -o ele_taiwan_10_100_500_moi.osm.pbf && \
    curl -k file:///root/osm_elevations/ele_taiwan_10_100_500_moi.osm.pbf.md5 -o ele_taiwan_10_100_500_moi.osm.pbf.md5 && \
    EXAM_FILE=/home/gps/taiwan-topo/download/osm_elevations/ele_taiwan_10_100_500_moi.osm.pbf; [ "$(md5sum $EXAM_FILE | cut -d' ' -f1)" == "$(cat ele_taiwan_10_100_500_moi.osm.pbf.md5 | cut -d' ' -f1)" ] || \
        ( rm -rf /home/gps/taiwan-topo/download/osm_elevations/ele_taiwan_10_100_500_moi.osm.pbf && false )
curl: (37) Couldn't open file /root/osm_elevations/ele_taiwan_10_100_500_moi.osm.pbf
^Cmake: *** [/home/gps/taiwan-topo/download/osm_elevations/ele_taiwan_10_100_500_moi.osm.pbf] Interrupt

由於我不是在$HOME下面編譯，是不是要修改路徑才能找到ele_taiwan_10_100_500_moi.osm.pbf？

**Comment by alpha-rudy** [comment]
嗨，@ayeteng 兄，你好。

太好了，我以為都沒有人在 compile 地圖。  ^^

也很抱歉，因為這些大檔案，超過 github 的檔案大小的限制，所以我都放在 dropbox 上下載。但，由於後來 dropbox 取消 direct URL download 的服務，導致無法下載，所以我直接放在 gcp 的 home directory 上。

我先打一包給你，讓你可以解開放在你的 home directory 下，應該就可以 compile 了。後續，我看看如何解決這些大檔案放置的問題。

謝謝回應喔！  :)

Rudy  9/30

**Comment by alpha-rudy** [comment]
Hi, @ayeteng 兄，

上傳了，請在下列位置下載後，untar 在你的 home directory 應該就可以了。請試試看。  :)

https://www.dropbox.com/s/f9boyl8ex2ez4gd/osm_elevations.tgz?dl=0

Thanks,
Rudy  9/30

**Comment by ayeteng** [comment]
謝謝你！經過大約一天的編譯，結果還是有點小問題：

Oct 01, 2017 12:26:48 PM org.mapsforge.map.writer.osmosis.MapFileWriterTask complete
INFO: start writing file...
Oct 01, 2017 12:31:28 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 100% of sub file for zoom interval index 0
Oct 01, 2017 12:32:18 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 10.0% of sub file for zoom interval index 1
Oct 01, 2017 12:32:22 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 20.0% of sub file for zoom interval index 1
Oct 01, 2017 12:35:31 PM org.mapsforge.map.writer.MapFileWriter writeSubfile
INFO: written 30.0% of sub file for zoom interval index 1
/bin/sh: line 11: 27226 Killed                  sh /home/gps/taiwan-topo/tools/osmosis/bin/osmosis --read-pbf "/home/gps/taiwan-topo/install/MOI_OSM_Taiwan_TOPO_Rudy_zls.osm.pbf" --buffer --mapfile-writer type=ram bbox=21.55682,118.12141,26.44212,122.31377 preferred-languages="zh,en" tag-conf-file="/home/gps/taiwan-topo/osm_scripts/tag-mapping.xml" polygon-clipping=true way-clipping=true label-position=true zoom-interval-conf=6,0,6,10,7,11,14,12,21 map-start-zoom=12 comment="2017.10.01  /  (c) Map: Rudy; Map data: OSM contributors; DEM data: Taiwan MOI" file="/home/gps/taiwan-topo/install/MOI_OSM_Taiwan_TOPO_Rudy.map"
make: *** [/home/gps/taiwan-topo/install/MOI_OSM_Taiwan_TOPO_Rudy.map] Error 137

[root@sw31 taiwan-topo]# make SUITE=taiwan mapsforge
make: Nothing to be done for `mapsforge'.
[root@sw31 taiwan-topo]# cd install/
[root@sw31 install]# ll
total 379396
-rw-r--r-- 1 root root    746815 Oct  1 12:31 MOI_OSM_Taiwan_TOPO_Rudy.map
-rw-r--r-- 1 root root 387759178 Oct  1 05:44 MOI_OSM_Taiwan_TOPO_Rudy_zls.osm.pbf

make產生error 137，map檔編譯到一半就停止了，似乎是記憶體用盡產生的問題？

**Comment by ayeteng** [comment]
果然是記憶體不足的原因，改用不同的機器就可以順利的完成編譯了。

INFO: estimated memory consumption: 25,722.78MB

**Comment by typebrook** [comment]
25G... 對機器的要求好像頗高

**Comment by alpha-rudy** [comment]
this issue should be closed. now.  ^^
