### ISSUE TITLE
Couldn't open file /Users/sam/osm_elevations/ele_taiwan_10_100_500_moi_v2018.3.osm.pbf

### ISSUE THREAD

**Issue by ayeteng** [alpha-rudy/taiwan-topo#29]
Hi Rudy大,

昨日看到高程檔瘦身的消息後趕快來更新地圖，發現編譯有問題，看來似乎要下載檔案，可以提供嗎？

 samteng@Sams-iMac  ~/Projects/taiwan-topo   master ●  make SUITE=taiwan mapsforge
[ -n "Taiwan" ]
mkdir -p /Users/sam/Projects/taiwan-topo/download/osm_elevations
cd /Users/sam/Projects/taiwan-topo/download/osm_elevations && \
	    curl -k file:///Users/sam/osm_elevations/ele_taiwan_10_100_500_moi_v2018.3.osm.pbf -o ele_taiwan_10_100_500_moi_v2018.3.osm.pbf && \
	    curl -k file:///Users/sam/osm_elevations/ele_taiwan_10_100_500_moi_v2018.3.osm.pbf.md5 -o ele_taiwan_10_100_500_moi_v2018.3.osm.pbf.md5 && \
	    EXAM_FILE=/Users/sam/Projects/taiwan-topo/download/osm_elevations/ele_taiwan_10_100_500_moi_v2018.3.osm.pbf; [ "$(md5 -q $EXAM_FILE)" == "$(cat ele_taiwan_10_100_500_moi_v2018.3.osm.pbf.md5 | cut -d' ' -f1)" ] || \
	    	( rm -rf /Users/sam/Projects/taiwan-topo/download/osm_elevations/ele_taiwan_10_100_500_moi_v2018.3.osm.pbf && false )
curl: (37) Couldn't open file /Users/sam/osm_elevations/ele_taiwan_10_100_500_moi_v2018.3.osm.pbf

**Comment by alpha-rudy** [comment]
Hi @ayeteng, 

Sorry, the local file is still a problem, because GitHub cannot put large files (without fee) and Dropbox cannot use direct links.  XD

I shared them at the following link, please download them, make a directory called `osm_elevations` and put all these files under this directory.

https://www.dropbox.com/sh/zek16veghjhs9d2/AAC3nfwMvilok9Fzaugjb0ZGa?dl=0

Thanks!  :)

Sincerely,
Rudy  8/13

**Comment by typebrook** [comment]
#30  加個說明吧,   之前好像也問過類似的問題 #27

**Comment by alpha-rudy** [comment]
thanks, @typebrook ！

**Comment by alpha-rudy** [comment]
Hi, @typebrook , will you join?  ^^

**Comment by typebrook** [comment]
@alpha-rudy  of course

**Comment by ayeteng** [comment]
之前的版本需要更大的記憶體，現在新的版本在我的MAC上面RAM=16G可以正確的編譯了，謝謝Rudy大神的分享

**Comment by alpha-rudy** [comment]
@ayeteng , you are welcomed.  ^^
