### ISSUE TITLE
Remove bridleway from styles

### ISSUE THREAD

**Issue by typebrook** [alpha-rudy/taiwan-topo#41]
Few ways in Taiwan feature `highway=bridleway`, and are not for hiking or horse-riding.
I think most of them are just mis-tagged

maybe it is unnecessary to use it in BN style? 38b417bab027dcb05a05c7afd6d013979b2307e2

see tagged features in https://overpass-turbo.eu/s/D9w

**Comment by alpha-rudy** [comment]
Done, thanks @typebrook !  :D
