### ISSUE TITLE
Include elevation PBF in this repo 

### ISSUE THREAD

**Issue by typebrook** [alpha-rudy/taiwan-topo#42]
Now we hold elevation countour PBFs (outdated open data) on Dropbox ([here](https://www.dropbox.com/sh/zek16veghjhs9d2/AAC3nfwMvilok9Fzaugjb0ZGa?dl=0))

Now There are two options could keep big binary files on GitHub, please reference docs at https://help.github.com/articles/distributing-large-binaries/
1. Release assets (no limit, single file < 2GB)
2. Git LFS

Since elevation contour data doesn't change frequently, I prefer to use git release.
And also, we can add milestone or more data in it.

**Comment by alpha-rudy** [comment]
嗨， @typebrook 兄，

謝謝你的建議，我測試了一下，發現 GitHub 的 Release 無法簡單的由 wget or curl 來下載，得連上網頁後，才能點擊下載。你知道方法嗎？

另，如果不行的話，我覺得可以利用 Rex 與 kcwu 的 mirror 來放 precompiled contours data，你覺得如何？

**Comment by typebrook** [comment]
方法當然有，範例如下，curl 記得加 `-L`

`https://github.com/[author]/[repo]/releases/download/[release]/[asset]`
e.g. 
`curl -LO https://github.com/browsh-org/browsh/releases/download/v1.5.0/browsh_1.5.0_linux_amd64.deb`

以上是針對使用者上傳的asset, source code使用
`https://github.com/[author]/[repo]/archive/[release].zip`
e.g.
`curl -LO https://github.com/browsh-org/browsh/archive/v1.5.0.zip`

ref:
https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository
https://api.github.com/repos/browsh-org/browsh/releases/assets/9574585

**Comment by typebrook** [comment]
原來你有建一個Draft 了，我把它正式發布，現在下載就OK囉
 (Release 可以隨時變更內容或刪除，不影響Repo）
`curl -LO https://github.com/alpha-rudy/taiwan-topo/releases/download/v1.0.0/ele_taiwan_10_100_500_moi_v2018.3_mix.o5m`

我猜因為在draft階段是不公開的，所以無法簡單透過指令下載

**Comment by alpha-rudy** [comment]
I will add the download later.  ^^

**Comment by alpha-rudy** [comment]
done, using the mirrors instead as the download throught of github is quite limited.

Thanks, @kcwu and @chihchun!
