### ISSUE TITLE
Tourism information

### ISSUE THREAD

**Issue by typebrook** [alpha-rudy/taiwan-topo#43]
Now we render all features with `k=tourism, v=information && k=information, v=any` with relatively large font size in low zoom level.
https://github.com/alpha-rudy/taiwan-topo/blob/aa19e79cfe1c84772a1760a540c06e233c1c3fce/styles/mapsforge_style/MOI_OSM.xml#L4289-L4307

Users report on facebook tha some features looks strange like this, which rex already made comment on it at https://www.openstreetmap.org/changeset/40800469#map=15/25.1772/121.5281
![jojo](https://user-images.githubusercontent.com/19887090/49162354-aa58e880-f365-11e8-8dff-813f7d139491.jpg)

Should we modify style or just change the tags for this kind of features?

**Comment by alpha-rudy** [comment]
Hi @typebrook ，我覺得 font 小一點，應該是合理的。就麻煩你囉！  ^^

**Comment by alpha-rudy** [comment]
Done with changing to small size.
