### ISSUE TITLE
等高線偏移

### ISSUE THREAD

**Issue by alpha-rudy** [alpha-rudy/taiwan-topo#50]
Reported by 何豪邁山友
"Rudy兄您好：
使用您的魯地圖這段期間，增添了我許多登山的方便與愉快，先致上十萬分謝意，我這陣子在電腦上瀏覽魯地圖時，會明顯發現：等高線都有往西偏的現象(第1張圖片)，原本以為是政府數值資料誤差所致，但今天我套用了happyman地圖瀏覽器的等高線2015(第2張圖片)，卻無偏移現象，不曉得是什麼原因造成的？請問未來的魯地圖有辦法做修正嗎？謝謝！"

第1張(請看玉山)
![52051115_2014579705335452_745025492683325440_n](https://user-images.githubusercontent.com/12744709/52908425-ad9ea900-32b0-11e9-8045-3802a14ee79b.png)

第2張(請看玉山)
![52297612_290537398295185_2492893267360743424_n](https://user-images.githubusercontent.com/12744709/52908429-c0b17900-32b0-11e9-934b-ff3f4dd7af97.png)

以下紅色圈選區域的等高線呈水平線，不知是否也是偏移造成的？
![51993381_401854370572887_3971943235164569600_n](https://user-images.githubusercontent.com/12744709/52908438-d161ef00-32b0-11e9-9f31-77d9b30763db.png)

**Comment by alpha-rudy** [comment]
透過 http://mc.basecamp.tw/#18/23.47003/120.95719 來看，2018 與 2016 的確存在差異。

<img width="1409" alt="screen shot 2019-02-17 at 12 43 32 pm" src="https://user-images.githubusercontent.com/12744709/52908498-fc007780-32b1-11e9-8a49-f9114697ae8e.png">

**Comment by alpha-rudy** [comment]
在玉山東方 (E121.01325°) 處，的確有條明顯的錯位，不曉得有沒有關聯？

<img width="1409" alt="screen shot 2019-02-17 at 12 50 57 pm" src="https://user-images.githubusercontent.com/12744709/52908545-f9eae880-32b2-11e9-9783-17c21785a16f.png">

**Comment by kcwu** [comment]
建議先釐清, 是高程資料有誤, 還是等高線轉換程式的問題

**Comment by alpha-rudy** [comment]
收到，我來檢視一下原始資料看看。

**Comment by alpha-rudy** [comment]
嗨, @kcwu , @chihchun, 

請教一下, 
1) 2016/dem_20m-wgs84v2.tif 沒有偏移
2) 2018/DEM_20m-wgs84-v3.tif 也沒有偏移

可是執行下面指令後，就偏移了。可能原因是什麼？  XD

$ gdal_merge.py -a_nodata -999 -co compress=LZW -of GTiff -o 2018/DEM_20m-wgs84-v4.tif 2016/dem_20m-wgs84v2.tif 2018/DEM_20m-wgs84-v3.tif

**Comment by kcwu** [comment]
我的直覺反應: gdal_merge.py 有 bug

**Comment by alpha-rudy** [comment]
嗯嗯，我試試看不同版本的 gdal_merge.py 來看看。或許還有其他工具可以執行 merge？

註：merge 的目的是因為 2018 DEM 含有空白區域（樂山空軍基地）

**Comment by alpha-rudy** [comment]
試了不同版本，也試了減少處理次數。還是不行。

```
$ gdal_merge.py --version
GDAL 2.4.0, released 2018/12/14
```

請問，有何建議嗎？  XD

**Comment by onibg** [comment]
rudy兄，辛苦您了！期待您的好消息喔：）

**Comment by alpha-rudy** [comment]
Yeah, the issue should have been worked around. ^^

By using a resampled 40m DEM (for a quick experiment), the contour lines look fitted by overlayed on the discrete rendered DEM.  

<img width="1070" alt="screen shot 2019-03-03 at 4 58 25 pm" src="https://user-images.githubusercontent.com/12744709/53693083-048a9f00-3dd6-11e9-8fa9-65d0265f990b.png">

<img width="1071" alt="screen shot 2019-03-03 at 4 57 54 pm" src="https://user-images.githubusercontent.com/12744709/53693086-0a808000-3dd6-11e9-92b8-7a25e10e4237.png">

<img width="1069" alt="screen shot 2019-03-03 at 4 57 21 pm" src="https://user-images.githubusercontent.com/12744709/53693087-0fddca80-3dd6-11e9-991b-78128a55d819.png">

<img width="1071" alt="screen shot 2019-03-03 at 4 56 56 pm" src="https://user-images.githubusercontent.com/12744709/53693089-13715180-3dd6-11e9-9c7c-93ebc9bbb5c2.png">

**Comment by alpha-rudy** [comment]
跟原來的版本相比，的確可以看到舊版的偏移。

<img width="1072" alt="screen shot 2019-03-03 at 5 10 31 pm" src="https://user-images.githubusercontent.com/12744709/53693178-d4440000-3dd7-11e9-92f9-6a27ec6214a4.png">

**Comment by alpha-rudy** [comment]
跟 NLSC 相比，看來吻合多了！(細緻度應該 DEM 20m 時，就會改善)  ^^

<img width="1071" alt="screen shot 2019-03-03 at 5 13 31 pm" src="https://user-images.githubusercontent.com/12744709/53693187-f63d8280-3dd7-11e9-90b8-51c3d19c0384.png">

**Comment by onibg** [comment]
謝謝魯大，看來很成功喔！請問是gdal_merge.py 有 bug嗎？

**Comment by alpha-rudy** [comment]
@delicadiesel ，可能吧。  XD

目前把 gdal_merge.py 貼上的部分，儘量的減小，問題就不明顯了。

**Comment by alpha-rudy** [comment]
另外，我決定把 contour line 製作的程序 open 出來。方便大家來檢視錯誤與改正（或是分工  XD）。

還沒完成喔，先不要 clone 或嘗試。  XD

https://github.com/alpha-rudy/taiwan-contour

**Comment by alpha-rudy** [comment]
租了一台高階 CPU 的雲端電腦。終於算出來了。看來結果還不錯。這周應該就可以收尾修正了。  ^^

玉山就定位了  XD
![offset](https://user-images.githubusercontent.com/12744709/53803799-caa9cc00-3f80-11e9-8bea-e710416e4728.png)

之前發現關刀山西峰西側的等高線水平位移消失了
![ex1](https://user-images.githubusercontent.com/12744709/53803802-d1384380-3f80-11e9-860a-8e4bd5d6bc8d.png)

之前司文豪兄發現丹大吊橋附近的地殼變動，也不震了  XD
![ex2](https://user-images.githubusercontent.com/12744709/53803808-d4333400-3f80-11e9-98c3-bc8de6eaca45.png)

**Comment by alpha-rudy** [comment]
Finally, I got this one done.  XD

The traditional version is fixed at v2019.03.07, and the lite version will be fixed at v2019.03.08. 

This issue is indeed high weight to me and no weigh at the same time for most of the people. How interesting.  XD

All previous versions of contour lines were made manually. Now, it was made a little more automatically, which is great. Cheer!

Two new repos for this issue, taiwan-dtm and rugis. Have fun.  ^^

Sincerely,
Rudy  3/8
