### ISSUE TITLE
Put URL of App's GitHub into App's About page

### ISSUE THREAD

**Issue by jidanni** [alpha-rudy/taiwan-topo#52]
建議 app 內 "About" 頁上加列綠野遊蹤之本 GitHub 網址，不要只有列別的 projects 的 github.

**Comment by alpha-rudy** [comment]
Hi, @jidanni , 你報錯案子了，這裡只有魯地圖相關的。  ^^

**Comment by jidanni** [comment]
那麼該於何 URL 報？ Thanks.
