### ISSUE TITLE
Put the Chinese name of the app also on to the English version About page

### ISSUE THREAD

**Issue by jidanni** [alpha-rudy/taiwan-topo#53]
另建議 app 內英文版 "About" 頁上加列「綠野遊蹤」四字。否則離線是，本國人家問我「那是什麼 app？」，除非我把整個手機切換中文，否則無法答覆。

**Comment by alpha-rudy** [comment]
嗨， @jidanni ，哈，你貼錯案子了吧。這只是魯地圖的案子而已。

**Comment by jidanni** [comment]
那麼該於何 URL 報？ Thanks.
