### ISSUE TITLE
新的林班地圖樣造成 mapsforge 0.6 噴錯 

### ISSUE THREAD

**Issue by chihchun** [alpha-rudy/taiwan-topo#57]
MOI_OSM.xml 的 1763 修改造成 [mapsforge rendering crash](https://gist.github.com/chihchun/ab75608ffb5e064775902d10733617dc)
`
        <caption k="compartment" priority="150" font-style="bold" font-size="12" fill="#0000FF" stroke="#E5FFFFFF" stroke-width="2"/>
`

**Comment by chihchun** [comment]
Rudy 做了一個自訂的 map file, 裡面有自動 key=compartment, 用來顯示林班地地號。由於沒有其他 tag 使用 compartment, 疑似 mapsforge map 裡面沒有 compartment keyboard 的 index, 造成 mapsforge render crash.

可能解法
- 升級 mapsforge render library，提高容錯性。
- 把 key=compartment 改成 key=ref
- 先在魯地圖的 tag-mapping.xml 上增加 new key，使新的魯地圖 map 檔產出 key=compartment 的 index

Rudy 會先測試在 tag-mapping.xml 上增加 new key.

**Comment by alpha-rudy** [comment]
嗯嗯，先試試方法三，如果可行的話，既可以相容舊版 rendor，也可以自由定義新的 keys。

> 先在魯地圖的 tag-mapping.xml 上增加 new key，使新的魯地圖 map 檔產出 key=compartment 的 index

MAP v2019.09.28 就會生效  ^^

**Comment by chihchun** [comment]
測試 Fri, 27 Sep 2019 18:27:31 GMT 這版， mapsforge 0.6 一樣會噴出 java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: invalid key: compartment

**Comment by alpha-rudy** [comment]
Hi @chihchun, 

I changed the key compartment to ref. Please let me know if the issue resolved or not. 

Thanks,
Rudy  9/30

**Comment by chihchun** [comment]
Hi, @alpha-rudy The new maps works today, tested with the daily build at 2019-10-01. 
Thanks for help!!

```
File: 'rudy/maps/MOI_OSM_Taiwan_TOPO_Rudy.map'
Size: 305789768 	Blocks: 589081     IO Block: 131072 regular file
Device: 73h/115d	Inode: 637164      Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2019-10-01 11:13:14.451504492 +0800
Modify: 2019-10-01 02:12:46.000000000 +0800
Change: 2019-10-01 06:00:08.660991135 +0800
Birth: -
```

**Comment by alpha-rudy** [comment]
Reported says that the fix result OruxMaps cannot display the "ref" label.

**Comment by alpha-rudy** [comment]
Ah, as far as I could remember, the ref issue was also fixed.  ^^
