### ISSUE TITLE
label for mountain peak disappears in z16

### ISSUE THREAD

**Issue by typebrook** [alpha-rudy/taiwan-topo#61]
I'll take time to handle this:
![output2](https://user-images.githubusercontent.com/19887090/88447960-5f111900-ce6b-11ea-855a-edfd21824b86.gif)

**Comment by alpha-rudy** [comment]
Hi, @typebrook , I believed this depend on render (APP). 

Should we close this issue?  ^^

**Comment by typebrook** [comment]
> Hi, @typebrook , I believed this depend on render (APP).
> 
> Should we close this issue? ^^

OK, I'll check what happened on GTs, it still cannot show some labels in some zoom levels
