### ISSUE TITLE
Embed version number to map file and style file

### ISSUE THREAD

**Issue by kcwu** [alpha-rudy/taiwan-topo#63]
常常看到使用者遇到的問題是, map file 或是 style file 沒有設定正確或是版本不對(或是 cache沒清掉). 使得大家花不少時間除錯. 
此外, 雖然有些 app 可以查看 map file 的版號, 但是各軟體的步驟不太一樣, 對一般使用者其實有點難度.

因此我提議, 在圖資內藏版號資訊, 所以將來可以跟使用者說(只是舉例)
> 請把地圖捲到台灣島最最東方凸出來那個地方, 縮放到看得到 "三貂角" 字樣的大小, 此時東邊海面上應該會有版號

實際技術細節:
 - map file 比較簡單, 就多放一個 node 到海面上, 使用跟"三貂角"一樣的 tag 就好了(`place:locality`). `name` 的部份要在產生 map file 的 script 內把版號寫進入.
 - style file 的話, 因為 icon 可以吃 svg 格式, 所以可以在海上放一個特別的 node 使用那個 svg icon. svg 是文字檔, 所以也容易使用 script 更新. 如果不方便用 svg 格式的話, 產生 png 檔應該也不會太大, 我猜幾十 kb 應該就夠了.

**Comment by alpha-rudy** [comment]
Hi, @kcwu 兄，好久不見，抱歉，沒看到你留下的 request。

倒也有一直想到這問題。我來進行。

map file version 是比較容易。我應該可以直接開始。

style file 的話，SVG 似乎有支援 text （不曉得 APP 相容性如何），我再多試試看。  ^^

**Comment by alpha-rudy** [comment]
I added map version, and gave up the style version. Let's close this unless anyone want to try style version.  ^^
